from tkinter import *
from tkinter import messagebox
w=Tk()
w.title('Number guessing game')
l1=Label(w,text='Welcome to the game')
l1.pack(pady=10)
l2=Label(w,text="What's your name?")
l2.pack()
f2=Frame(w)
f2.pack()
e1=Entry(f2,width=12)
e1.grid(row=0,column=0,padx=29)
b1=Button(f2,text='OK',command=NONE)
b1.grid(row=0,column=1)
f=Frame(w)
f.pack()
l3=Label(f,text='Your Guess:')
l3.grid(row=0,column=0)
e2=Entry(f,width=5)
e2.grid(row=0,column=1,padx=16)
b2=Button(f,text='OK',command=NONE)
b2.grid(row=0,column=2)
mainloop()