from tkinter import *
w=Tk()
w.title('Flavour Selection')
t=Label(w,text='Flavour Seclection',fg='red')
t.pack()
f=Frame(w)
f.pack()
b1=Button(f,text='Ice cream')
b1.grid(row=0,column=0,padx=5)
b2=Button(f,text='Crepe')
b2.grid(row=0,column=1,padx=5)
b3=Button(f,text='Waffle')
b3.grid(row=0,column=2)
mainloop()
