from tkinter import *
w=Tk()
w.title('Flavour Selection')
t=Label(w,text='Flavour Seclection',fg='red')
t.pack()
f=Frame(w)
f.pack()
b1=Button(f,text='Ice cream')
b1.grid(row=0,column=0,padx=5)
b2=Button(f,text='Crepe')
b2.grid(row=0,column=1,padx=5)
b3=Button(f,text='Waffle')
b3.grid(row=0,column=2)
#2nd frame
f2=Frame(w)
f2.pack(pady=5)
b4=Button(f2,text='Nutella')
b4.grid(row=0,column=0)
b5=Button(f2,text='Vanilla')
b5.grid(row=1,column=0)
b6=Button(f2,text='Strawberry')
b6.grid(row=2,column=0)
mainloop()
