from tkinter import *
import calendar
w=Tk()
w.title('Calendar')
def year():
    c=Tk()
    c.config(bg='Grey')
    fetchy=int(e.get())
    cont=calendar.calendar(fetchy)
    text=Text(c,font='Consolas 10',wrap='none',height=60,width=80)
    text.insert('1.0',cont)
    text.config(state='disabled')
    text.pack()
    c.mainloop()
t=Label(w,text='Calendar',bg='gray',font=('Arial',25,'normal'))
l=Label(w,text='Enter year',font=('Arial',15,'normal'))
e=Entry(w,width=5,font=('Arial',15,'normal'))
b1=Button(w,text='Enter',command=year)
be=Button(w,text='Exit',command=w.destroy)
t.pack()
l.pack()
e.pack()
b1.pack()
be.pack()
mainloop()