from tkinter import *
w=Tk()
w.title('Weight Converter')
def convert():
    fetchg=float(evalue.get()*1000)
    textg.delete('1.0',END)
    textg.insert('1.0',fetchg)
    fetchp=float(evalue.get()*2.205)
    textp.delete('1.0',END)
    textp.insert('1.0',fetchp)
    fetcho=float(evalue.get()*35.274)
    texto.delete('1.0',END)
    texto.insert('1.0',fetcho)
textg=Text(w,font=('arial',20))
textg.grid(row=2,column=0)
textp=Text(w,font=('arial',20))
textp.grid(row=2,column=1)
texto=Text(w,font=('arial',20))
texto.grid(row=2,column=2)
l1=Label(w,text='Enter the weight in KG',font=('Arial',20))
l1.grid(row=0,column=0)
evalue=StringVar()
e=Entry(w,width=10,font=('arial',20),textvariable=evalue)
e.grid(row=0,column=1)
b=Button(w,text='Convert',command=convert)
b.grid(row=0,column=2)
l2=Label(w,text='Grams',font=('arial',20))
l2.grid(row=1,column=0)
l3=Label(w,text='Pounds',font=('arial',20))
l3.grid(row=1,column=1)
l4=Label(w,text='Ounces',font=('arial',20))
l4.grid(row=1,column=2)
mainloop()